export const TshirtData = [
   {
      id: 1,
      title: 'Item Title 1',
      price: 50,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/mens.jpg',
      path: '/item1',
      desc: 'item description',
      arr: ['/img/mens.jpg', '/img/gifts.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 2,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/mens.jpg',
      path: '/item2',
      desc: 'item description',
   },
   {
      id: 3,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/mens.jpg',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 4,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/mens.jpg',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 5,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/mens.jpg',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 6,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/mens.jpg',
      path: '/item6',
      desc: 'item description'
   },
]

export const HoodieData = [
   {
      id: 7,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/Tommy Hilfiger Hoodie.jpeg',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 8,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/Tommy Hilfiger Hoodie.jpeg',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 9,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/Tommy Hilfiger Hoodie.jpeg',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 10,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/Tommy Hilfiger Hoodie.jpeg',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 11,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/Tommy Hilfiger Hoodie.jpeg',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 12,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/Tommy Hilfiger Hoodie.jpeg',
      path: '/item6',
      desc: 'item description'
   },
]

export const OuterwearData = [
   {
      id: 13,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/gifts.jpg',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 14,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/gifts.jpg',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 15,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/gifts.jpg',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 16,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/gifts.jpg',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 17,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/gifts.jpg',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 18,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/gifts.jpg',
      path: '/item6',
      desc: 'item description'
   },
]

export const CrossBodyBagsData = [
   {
      id: 19,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 20,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 21,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 22,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 23,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 24,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const BackpacksData = [
   {
      id: 25,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 26,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 27,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 28,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 29,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 30,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const SneakersData = [
   {
      id: 31,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 32,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 33,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 34,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 35,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 36,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const SlidesSandalsData = [
   {
      id: 37,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 38,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 39,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 40,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 41,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 42,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const JewelryData = [
   {
      id: 43,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 44,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 45,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 46,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 47,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 48,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const SunglassesData = [
   {
      id: 49,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 50,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 51,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 52,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 53,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 54,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const BeltsData = [
   {
      id: 55,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 56,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 57,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 58,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 59,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 60,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]