export const TshirtData = [
   {
      id: 1,
      title: 'Givenchy Logo Tee',
      price: 850,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/Givenchy Tee.jpeg',
      path: '/givenchy-logo-tee',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 2,
      title: 'Tommy Hilfiger Logo Tee',
      price: 70,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/Tommy Hilfiger Tee.jpg',
      path: '/tommy-hilfiger-logo-tee',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/Tommy Hilfiger Tee.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 3,
      title: 'Calvin Klein Tee',
      price: 65,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/Calvin Klein Tee.jpg',
      path: '/calvin-klein-tee',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/Calvin Klein Tee.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 4,
      title: 'POLO Logo Tee',
      price: 60,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/POLO Tee.jpg',
      path: '/polo-logo-tee',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/POLO Tee.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 5,
      title: 'Lacoste Signature Tee',
      price: 40,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/Lacoste Tee.jpg',
      path: '/lacoste-signature-tee',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/Lacoste Tee.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 6,
      title: 'BURBERRY Logo Tee',
      price: 515,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/BURBERRY Tee.png',
      path: '/burberry-logo-tee',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/BURBERRY Tee.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const HoodieData = [
   {
      id: 7,
      title: 'Tommy Hilfiger Logo Hoodie',
      price: 170,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/Tommy Hilfiger Hoodie.jpeg',
      path: '/tommy-hilfiger-logo-hoodie',
      desc: 'item description',
      arr: ['/img/Tommy Hilfiger Hoodie.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 8,
      title: 'Armani Exchange Logo Hoodie',
      price: 180,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/Armani Hoodie.png',
      path: '/armani-exchange-logo-hoodie',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/Armani Hoodie.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 9,
      title: 'Gucci Hoodie',
      price: 1250,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/Gucci Hoodie.png',
      path: '/gucci-hoodie',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/Gucci Hoodie.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 10,
      title: 'KENZO Sweatshirt',
      price: 330,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/KENZO Sweatshirt.png',
      path: '/kenzo-sweatshirt',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/KENZO Sweatshirt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 11,
      title: 'Givenchy Sweatshirt',
      price: 1300,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/Givenchy Sweatshirt.png',
      path: '/givenchy-sweatshirt',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/Givenchy Sweatshirt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 12,
      title: 'Tommy Hilfiger Graphic Logo Sweatshirt',
      price: 250,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/Tommy Hilfiger Sweatshirt.png',
      path: '/tommy-hilfiger-graphic-logo-sweatshirt',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/Tommy Hilfiger Sweatshirt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const OuterwearData = [
   {
      id: 13,
      title: 'The North Face Puffer Jacket',
      price: 390,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/North Face Puffer Jacket.png',
      path: '/north-face-puffer-jacket',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/North Face Puffer Jacket.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 14,
      title: 'Oubre Jacket',
      price: 160,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Oubre Jacket.png',
      path: '/oubre-jacket',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Oubre Jacket.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 15,
      title: 'Dolce & Gabanna Jacket',
      price: 1100,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Dolce & Gabanna Jacket.png',
      path: '/dolce-gabanna-jacket',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Dolce & Gabanna Jacket.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 16,
      title: 'Liquor & Poker Trucker Jacket',
      price: 110,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Liquor & Poker Trucker Jacket.png',
      path: '/liquor-poker-trucker-jacket',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Liquor & Poker Trucker Jacket.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 17,
      title: 'Vintage Jacket',
      price: 80,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Vintage Jacket.jpg',
      path: '/vintage-jacket',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Vintage Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 18,
      title: 'Prada Pattern Jacket',
      price: 800,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg',
      path: '/prada-pattern-jacket',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const CrossBodyBagsData = [
   {
      id: 19,
      title: 'Adidas Essential Cross-body',
      price: 45,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '/img/MENS/CROSS-BODY-BAGS/Adidas Festival Cross-body.jpeg',
      path: '/adidas-essential-crossbody',
      desc: 'item description',
      arr: ['/img/MENS/CROSS-BODY-BAGS/Adidas Festival Cross-body.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 20,
      title: 'Tommy Hilfiger Cross-Body',
      price: 120,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '/img/MENS/CROSS-BODY-BAGS/Tommy Hilfiger Cross-Body Bag.png',
      path: '/tommy-hilfiger-crossbody',
      desc: 'item description',
      arr: ['/img/MENS/CROSS-BODY-BAGS/Tommy Hilfiger Cross-Body Bag.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 21,
      title: 'Gucci Cross-Body',
      price: 1150,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '/img/MENS/CROSS-BODY-BAGS/Gucci Cross-Body.png',
      path: '/gucci-crossbody',
      desc: 'item description',
      arr: ['/img/MENS/CROSS-BODY-BAGS/Gucci Cross-Body.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 22,
      title: 'Nike Cross-Body',
      price: 80,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '/img/MENS/CROSS-BODY-BAGS/Nike Cross-Body.png',
      path: '/nike-crossbody',
      desc: 'item description',
      arr: ['/img/MENS/CROSS-BODY-BAGS/Nike Cross-Body.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 23,
      title: 'Tommy Hilfiger Essential Mini',
      price: 120,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '/img/MENS/CROSS-BODY-BAGS/Tommy Hilfiger Essential Mini.png',
      path: '/tommy-hilfiger-essential-mini',
      desc: 'item description',
      arr: ['/img/MENS/CROSS-BODY-BAGS/Tommy Hilfiger Essential Mini.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 24,
      title: 'Calvin Klein Cross-Body',
      price: 140,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '/img/MENS/CROSS-BODY-BAGS/Calvin Klein Cross-Body.png',
      path: '/calvin-klein-crossbody',
      desc: 'item description',
      arr: ['/img/MENS/CROSS-BODY-BAGS/Calvin Klein Cross-Body.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const BackpacksData = [
   {
      id: 25,
      title: 'Fendi Backpack',
      price: 1150,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '/img/MENS/BACKPACKS/Fendi Backpack.png',
      path: '/fendi-backpack',
      desc: 'item description',
      arr: ['/img/MENS/BACKPACKS/Fendi Backpack.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 26,
      title: 'Tommy Hilfiger Mini Backpack',
      price: 120,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '/img/MENS/BACKPACKS/Tommy Hilfiger Mini Backpack.png',
      path: '/tommy-hilfiger-mini-backpack',
      desc: 'item description',
      arr: ['/img/MENS/BACKPACKS/Tommy Hilfiger Mini Backpack.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 27,
      title: 'Calvin Klein Backpack',
      price: 250,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '/img/MENS/BACKPACKS/Calvin Klein Backpack.png',
      path: '/calvin-klein-backpack',
      desc: 'item description',
      arr: ['/img/MENS/BACKPACKS/Calvin Klein Backpack.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 28,
      title: 'Tommy Hilfiger Backpack Blue',
      price: 180,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '/img/MENS/BACKPACKS/Tommy Hilfiger Backpack Blue.png',
      path: '/tommy-hilfiger-backpack-blue',
      desc: 'item description',
      arr: ['/img/MENS/BACKPACKS/Tommy Hilfiger Backpack Blue.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 29,
      title: 'Billabong Backpack',
      price: 40,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '/img/MENS/BACKPACKS/Billabong Backpack.png',
      path: '/billabong-backpack',
      desc: 'item description',
      arr: ['/img/MENS/BACKPACKS/Billabong Backpack.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 30,
      title: 'Gucci Backpack',
      price: 2500,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '/img/MENS/BACKPACKS/Gucci Backpack.png',
      path: '/gucci-backpack',
      desc: 'item description',
      arr: ['/img/MENS/BACKPACKS/Gucci Backpack.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const SneakersData = [
   {
      id: 31,
      title: 'Carnaby Evo Sneakers',
      price: 160,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '/img/MENS/SNEAKERS/Carnaby Evo Sneakers.png',
      path: '/carnaby-evo-sneakers',
      desc: 'item description',
      arr: ['/img/MENS/SNEAKERS/Carnaby Evo Sneakers.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 32,
      title: 'GIVENCHY Sneakers',
      price: 850,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '/img/MENS/SNEAKERS/GIVENCHY Sneakers.png',
      path: '/givenchy-sneakers',
      desc: 'item description',
      arr: ['/img/MENS/SNEAKERS/GIVENCHY Sneakers.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 33,
      title: 'Gucci Ace Sneakers',
      price: 1200,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '/img/MENS/SNEAKERS/Gucci Ace Sneakers.png',
      path: '/gucci-ace-sneakers',
      desc: 'item description',
      arr: ['/img/MENS/SNEAKERS/Gucci Ace Sneakers.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 34,
      title: 'LV Trainer 2',
      price: 2800,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '/img/MENS/SNEAKERS/LV Trainer 2.png',
      path: '/lv-trainer-2',
      desc: 'item description',
      arr: ['/img/MENS/SNEAKERS/LV Trainer 2.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 35,
      title: 'Tommy Hilfiger Sneakers',
      price: 180,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '/img/MENS/SNEAKERS/Tommy Hilfiger Sneakers.png',
      path: '/tommy-hilfiger-sneakers',
      desc: 'item description',
      arr: ['/img/MENS/SNEAKERS/Tommy Hilfiger Sneakers.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 36,
      title: 'Jordan Military 4s',
      price: 270,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '/img/MENS/SNEAKERS/Jordan Military 4s.png',
      path: '/jordan-military-4s',
      desc: 'item description',
      arr: ['/img/MENS/SNEAKERS/Jordan Military 4s.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const SlidesSandalsData = [
   {
      id: 37,
      title: 'Lacoste Slides',
      price: 50,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '/img/MENS/SLIDES & SANDALS/Lacoste Slides.png',
      path: '/lacoste-slides',
      desc: 'item description',
      arr: ['/img/MENS/SLIDES & SANDALS/Lacoste Slides.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 38,
      title: 'Gucci Slides',
      price: 600,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '/img/MENS/SLIDES & SANDALS/Gucci Slides.png',
      path: '/gucci-slides',
      desc: 'item description',
      arr: ['/img/MENS/SLIDES & SANDALS/Gucci Slides.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 39,
      title: 'Givenchy Slides',
      price: 650,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '/img/MENS/SLIDES & SANDALS/Givenchy Slides.png',
      path: '/givenchy-slides',
      desc: 'item description',
      arr: ['/img/MENS/SLIDES & SANDALS/Givenchy Slides.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 40,
      title: 'Nike Victori Slides',
      price: 45,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '/img/MENS/SLIDES & SANDALS/Nike Victori Slides.png',
      path: '/nike-victori-slides',
      desc: 'item description',
      arr: ['/img/MENS/SLIDES & SANDALS/Nike Victori Slides.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 41,
      title: 'Adidas Slides',
      price: 40,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '/img/MENS/SLIDES & SANDALS/Adidas Slides.png',
      path: '/adidas-slides',
      desc: 'item description',
      arr: ['/img/MENS/SLIDES & SANDALS/Adidas Slides.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 42,
      title: 'Gucci Brown Slides',
      price: 750,
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '/img/MENS/SLIDES & SANDALS/Gucci Brown Slides.png',
      path: '/gucci-brown-slides',
      desc: 'item description',
      arr: ['/img/MENS/SLIDES & SANDALS/Gucci Brown Slides.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const JewelryData = [
   {
      id: 43,
      title: 'Helloice Cuban Link Chain',
      price: 390,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '/img/MENS/JEWELRY/Helloice Cuban Link Chain.png',
      path: '/helloice-cuban-link-chain',
      desc: 'item description',
      arr: ['/img/MENS/JEWELRY/Helloice Cuban Link Chain.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 44,
      title: 'Viking Steel Rings',
      price: 30,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '/img/MENS/JEWELRY/Viking Steel Rings.png',
      path: '/viking-steel-rings',
      desc: 'item description',
      arr: ['/img/MENS/JEWELRY/Viking Steel Rings.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 45,
      title: 'Rhinestone Cuban Link Chain',
      price: 50,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '/img/MENS/JEWELRY/Rhinestone Cuban Link Chain.png',
      path: '/rhinestone-cuban-link-chain',
      desc: 'item description',
      arr: ['/img/MENS/JEWELRY/Rhinestone Cuban Link Chain.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 46,
      title: 'Miami Cuban Link Bracelet',
      price: 5200,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '/img/MENS/JEWELRY/Miami Cuban Link Bracelet.png',
      path: '/miami-cuban-link-bracelet',
      desc: 'item description',
      arr: ['/img/MENS/JEWELRY/Miami Cuban Link Bracelet.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 47,
      title: 'Diamond Watch',
      price: 900,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '/img/MENS/JEWELRY/Diamond Watch.png',
      path: '/diamond-watch',
      desc: 'item description',
      arr: ['/img/MENS/JEWELRY/Diamond Watch.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 48,
      title: 'Nike Gold Rings',
      price: 350,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '/img/MENS/JEWELRY/Nike Gold Rings.png',
      path: '/nike-gold-rings',
      desc: 'item description',
      arr: ['/img/MENS/JEWELRY/Nike Gold Rings.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const SunglassesData = [
   {
      id: 49,
      title: 'Bvlgari Sunglasses',
      price: 1200,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '/img/MENS/SUNGLASSES/Bulgari Sunglasses.png',
      path: '/bvlgari-sunglasses',
      desc: 'item description',
      arr: ['/img/MENS/SUNGLASSES/Bulgari Sunglasses.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 50,
      title: 'Dior Sunglasses',
      price: 1500,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '/img/MENS/SUNGLASSES/Dior Sunglasses.png',
      path: '/dior-sunglasses',
      desc: 'item description',
      arr: ['/img/MENS/SUNGLASSES/Dior Sunglasses.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 51,
      title: 'Versace Sunglasses',
      price: 450,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '/img/MENS/SUNGLASSES/Versace Sunglasses.png',
      path: '/versace-sunglasses',
      desc: 'item description',
      arr: ['/img/MENS/SUNGLASSES/Versace Sunglasses.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 52,
      title: 'Louis Vuitton Sunglasses',
      price: 650,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '/img/MENS/SUNGLASSES/Louis Vuitton Sunglasses.png',
      path: '/louis-vuitton-sunglasses',
      desc: 'item description',
      arr: ['/img/MENS/SUNGLASSES/Louis Vuitton Sunglasses.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 53,
      title: 'Oakley Sunglasses',
      price: 140,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '/img/MENS/SUNGLASSES/Oakley Sunglasses.png',
      path: '/oakley-sunglasses',
      desc: 'item description',
      arr: ['/img/MENS/SUNGLASSES/Oakley Sunglasses.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 54,
      title: 'Ray Bans Sunglasses',
      price: 180,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '/img/MENS/SUNGLASSES/Ray Bans Sunglasses.png',
      path: '/ray-bans-sunglasses',
      desc: 'item description',
      arr: ['/img/MENS/SUNGLASSES/Ray Bans Sunglasses.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const BeltsData = [
   {
      id: 55,
      title: 'Louis Vuitton Belt',
      price: 850,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '/img/MENS/BELTS/Louis Vuitton Belt.png',
      path: '/louis-vuitton-belt',
      desc: 'item description',
      arr: ['/img/MENS/BELTS/Louis Vuitton Belt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 56,
      title: 'Gucci Belt',
      price: 750,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '/img/MENS/BELTS/Gucci Belt.png',
      path: '/gucci-belt',
      desc: 'item description',
      arr: ['/img/MENS/BELTS/Gucci Belt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 57,
      title: 'Versace Belt',
      price: 650,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '/img/MENS/BELTS/Versace Belt.png',
      path: '/versace-belt',
      desc: 'item description',
      arr: ['/img/MENS/BELTS/Versace Belt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 58,
      title: 'Givenchy Belt',
      price: 550,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '/img/MENS/BELTS/Givenchy Belt.png',
      path: '/givenchy-belt',
      desc: 'item description',
      arr: ['/img/MENS/BELTS/Givenchy Belt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 59,
      title: 'Fendi Belt',
      price: 500,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '/img/MENS/BELTS/Fendi Belt.png',
      path: '/fendi-belt',
      desc: 'item description',
      arr: ['/img/MENS/BELTS/Fendi Belt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 60,
      title: 'Balenciaga Belt',
      price: 1150,
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '/img/MENS/BELTS/Balenciaga Belt.png',
      path: '/balenciaga-belt',
      desc: 'item description',
      arr: ['/img/MENS/BELTS/Balenciaga Belt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]