export const TshirtData = [
   {
      id: 1,
      title: 'Givenchy Logo Tee',
      price: 850,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/Givenchy Tee.jpeg',
      path: '/item1',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 2,
      title: 'Tommy Hilfiger Logo Tee',
      price: 70,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/Tommy Hilfiger Tee.jpg',
      path: '/item2',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/Tommy Hilfiger Tee.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 3,
      title: 'Calvin Klein Tee',
      price: 65,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/Calvin Klein Tee.jpg',
      path: '/item3',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/Calvin Klein Tee.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 4,
      title: 'POLO Logo Tee',
      price: 60,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/POLO Tee.jpg',
      path: '/item4',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/POLO Tee.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 5,
      title: 'Lacoste Signature Tee',
      price: 40,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/Lacoste Tee.jpg',
      path: '/item5',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/Lacoste Tee.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 6,
      title: 'BURBERRY Logo Tee',
      price: 515,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'T-Shirts',
      linkcategory: 't-shirts',
      src: '/img/MENS/T-SHIRTS/BURBERRY Tee.png',
      path: '/item6',
      desc: 'item description',
      arr: ['/img/MENS/T-SHIRTS/BURBERRY Tee.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const HoodieData = [
   {
      id: 7,
      title: 'Tommy Hilfiger Logo Hoodie',
      price: 170,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/Tommy Hilfiger Hoodie.jpeg',
      path: '/item1',
      desc: 'item description',
      arr: ['/img/Tommy Hilfiger Hoodie.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 8,
      title: 'Armani Exchange Logo Hoodie',
      price: 180,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/Armani Hoodie.png',
      path: '/item2',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/Armani Hoodie.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 9,
      title: 'Gucci Hoodie',
      price: 1250,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/Gucci Hoodie.png',
      path: '/item3',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/Gucci Hoodie.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 10,
      title: 'KENZO Sweatshirt',
      price: 330,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/KENZO Sweatshirt.png',
      path: '/item4',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/KENZO Sweatshirt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 11,
      title: 'Givenchy Sweatshirt',
      price: 1300,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/Givenchy Sweatshirt.png',
      path: '/item5',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/Givenchy Sweatshirt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 12,
      title: 'Tommy Hilfiger Graphic Logo Sweatshirt',
      price: 250,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Sweatshirts & Hoodies',
      linkcategory: 'sweats-hoodies',
      src: '/img/MENS/SWEATSHIRTS & HOODIES/Tommy Hilfiger Sweatshirt.png',
      path: '/item6',
      desc: 'item description',
      arr: ['/img/MENS/SWEATSHIRTS & HOODIES/Tommy Hilfiger Sweatshirt.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const OuterwearData = [
   {
      id: 13,
      title: 'The North Face Puffer Jacket',
      price: 390,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/North Face Puffer Jacket.png',
      path: '/item1',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/North Face Puffer Jacket.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 14,
      title: 'Oubre Jacket',
      price: 160,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Oubre Jacket.png',
      path: '/item2',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Oubre Jacket.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 15,
      title: 'Dolce & Gabanna Jacket',
      price: 1100,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Dolce & Gabanna Jacket.png',
      path: '/item3',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Dolce & Gabanna Jacket.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 16,
      title: 'Liquor & Poker Trucker Jacket',
      price: 110,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Liquor & Poker Trucker Jacket.png',
      path: '/item4',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Liquor & Poker Trucker Jacket.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 17,
      title: 'Vintage Jacket',
      price: 80,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Vintage Jacket.jpg',
      path: '/item5',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Vintage Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 18,
      title: 'Prada Pattern Jacket',
      price: 800,
      gender: 'mens',
      categories: 'READY-TO-WEAR',
      category: 'Jackets & Coats',
      linkcategory: 'jackets-coats',
      src: '/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg',
      path: '/item6',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const CrossBodyBagsData = [
   {
      id: 19,
      title: 'Adidas Essential Cbody',
      price: 45,
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '/img/MENS/CROSS-BODY-BAGS/Adidas Festival Crossbody.jpeg',
      path: '/item1',
      desc: 'item description',
      arr: ['/img/MENS/CROSS-BODY-BAGS/Adidas Festival Crossbody.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 20,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item2',
      desc: 'item description',
      arr: ['/img/MENS/CROSS-BODY-BAGS/Gucci Cross Body.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 21,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item3',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 22,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item4',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 23,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item5',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 24,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Cross-Body Bags',
      linkcategory: 'cross-body-bags',
      src: '',
      path: '/item6',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const BackpacksData = [
   {
      id: 25,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item1',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 26,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item2',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 27,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item3',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 28,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item4',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 29,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item5',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      id: 30,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'BAGS',
      category: 'Backpacks',
      linkcategory: 'backpacks',
      src: '',
      path: '/item6',
      desc: 'item description',
      arr: ['/img/MENS/JACKETS & COATS/Prada Pattern Jacket.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const SneakersData = [
   {
      id: 31,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 32,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 33,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 34,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 35,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 36,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Sneakers',
      linkcategory: 'sneakers',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const SlidesSandalsData = [
   {
      id: 37,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 38,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 39,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 40,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 41,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 42,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'SHOES',
      category: 'Slides & Sandals',
      linkcategory: 'slides-sandals',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const JewelryData = [
   {
      id: 43,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 44,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 45,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 46,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 47,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 48,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Jewelry',
      linkcategory: 'jewelry',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const SunglassesData = [
   {
      id: 49,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 50,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 51,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 52,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 53,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 54,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Sunglasses',
      linkcategory: 'sunglasses',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]

export const BeltsData = [
   {
      id: 55,
      title: 'Item Title 1',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item1',
      desc: 'item description'
   },
   {
      id: 56,
      title: 'Item Title 2',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item2',
      desc: 'item description'
   },
   {
      id: 57,
      title: 'Item Title 3',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item3',
      desc: 'item description'
   },
   {
      id: 58,
      title: 'Item Title 4',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item4',
      desc: 'item description'
   },
   {
      id: 59,
      title: 'Item Title 5',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item5',
      desc: 'item description'
   },
   {
      id: 60,
      title: 'Item Title 6',
      price: 'Price',
      gender: 'mens',
      categories: 'ACCESSORIES',
      category: 'Belts',
      linkcategory: 'belts',
      src: '',
      path: '/item6',
      desc: 'item description'
   },
]