export const WomensTshirtsData = [
   {
      'id': 61,
      'title': 'Item Title 1',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'T-Shirts',
      'linkcategory': 't-shirts',
      'src': '',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 62,
      'title': 'Item Title 2',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'T-Shirts',
      'linkcategory': 't-shirts',
      'src': '',
      'path': '/item2',
      'desc': 'item description'
   },
   {
      'id': 63,
      'title': 'Item Title 3',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'T-Shirts',
      'linkcategory': 't-shirts',
      'src': '',
      'path': '/item3',
      'desc': 'item description'
   },
   {
      'id': 64,
      'title': 'Item Title 4',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'T-Shirts',
      'linkcategory': 't-shirts',
      'src': '',
      'path': '/item4',
      'desc': 'item description'
   },
   {
      'id': 65,
      'title': 'Item Title 5',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'T-Shirts',
      'linkcategory': 't-shirts',
      'src': '',
      'path': '/item5',
      'desc': 'item description'
   },
   {
      'id': 66,
      'title': 'Item Title 6',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'T-Shirts',
      'linkcategory': 't-shirts',
      'src': '',
      'path': '/item6',
      'desc': 'item description'
   },
]

export const WomensHoodieData = [
   {
      'id': 67,
      'title': 'Item Title 1',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Sweatshirts & Hoodies',
      'linkcategory': 'sweats-hoodies',
      'src': '',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 68,
      'title': 'Item Title 2',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Sweatshirts & Hoodies',
      'linkcategory': 'sweats-hoodies',
      'src': '',
      'path': '/item2',
      'desc': 'item description'
   },
   {
      'id': 69,
      'title': 'Item Title 3',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Sweatshirts & Hoodies',
      'linkcategory': 'sweats-hoodies',
      'src': '',
      'path': '/item3',
      'desc': 'item description'
   },
   {
      'id': 70,
      'title': 'Item Title 4',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Sweatshirts & Hoodies',
      'linkcategory': 'sweats-hoodies',
      'src': '',
      'path': '/item4',
      'desc': 'item description'
   },
   {
      'id': 71,
      'title': 'Item Title 5',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Sweatshirts & Hoodies',
      'linkcategory': 'sweats-hoodies',
      'src': '',
      'path': '/item5',
      'desc': 'item description'
   },
   {
      'id': 72,
      'title': 'Item Title 6',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Sweatshirts & Hoodies',
      'linkcategory': 'sweats-hoodies',
      'src': '',
      'path': '/item6',
      'desc': 'item description'
   },
]

export const WomensOuterwearData = [
   {
      'id': 73,
      'title': 'Item Title 1',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Outerwear & Blousons',
      'linkcategory': 'outerwear-blousons',
      'src': '',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 74,
      'title': 'Item Title 2',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Outerwear & Blousons',
      'linkcategory': 'outerwear-blousons',
      'src': '',
      'path': '/item2',
      'desc': 'item description'
   },
   {
      'id': 75,
      'title': 'Item Title 3',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Outerwear & Blousons',
      'linkcategory': 'outerwear-blousons',
      'src': '',
      'path': '/item3',
      'desc': 'item description'
   },
   {
      'id': 76,
      'title': 'Item Title 4',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Outerwear & Blousons',
      'linkcategory': 'outerwear-blousons',
      'src': '',
      'path': '/item4',
      'desc': 'item description'
   },
   {
      'id': 77,
      'title': 'Item Title 5',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Outerwear & Blousons',
      'linkcategory': 'outerwear-blousons',
      'src': '',
      'path': '/item5',
      'desc': 'item description'
   },
   {
      'id': 78,
      'title': 'Item Title 6',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'READY-TO-WEAR',
      'category': 'Outerwear & Blousons',
      'linkcategory': 'outerwear-blousons',
      'src': '',
      'path': '/item6',
      'desc': 'item description'
   },
]

export const WomensShoulderBagsData = [
   {
      'id': 79,
      'title': 'Item Title 1',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Shoulder Bags',
      'linkcategory': 'shoulder-bags',
      'src': '',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 80,
      'title': 'Item Title 2',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Shoulder Bags',
      'linkcategory': 'shoulder-bags',
      'src': '',
      'path': '/item2',
      'desc': 'item description'
   },
   {
      'id': 81,
      'title': 'Item Title 3',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Shoulder Bags',
      'linkcategory': 'shoulder-bags',
      'src': '',
      'path': '/item3',
      'desc': 'item description'
   },
   {
      'id': 82,
      'title': 'Item Title 4',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Shoulder Bags',
      'linkcategory': 'shoulder-bags',
      'src': '',
      'path': '/item4',
      'desc': 'item description'
   },
   {
      'id': 83,
      'title': 'Item Title 5',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Shoulder Bags',
      'linkcategory': 'shoulder-bags',
      'src': '',
      'path': '/item5',
      'desc': 'item description'
   },
   {
      'id': 84,
      'title': 'Item Title 6',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Shoulder Bags',
      'linkcategory': 'shoulder-bags',
      'src': '',
      'path': '/item6',
      'desc': 'item description'
   },
]

export const WomensMicroBagsData = [
   {
      'id': 85,
      'title': 'Item Title 1',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Micro Bags',
      'linkcategory': 'micro-bags',
      'src': '',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 86,
      'title': 'Item Title 2',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Micro Bags',
      'linkcategory': 'micro-bags',
      'src': '',
      'path': '/item2',
      'desc': 'item description'
   },
   {
      'id': 87,
      'title': 'Item Title 3',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Micro Bags',
      'linkcategory': 'micro-bags',
      'src': '',
      'path': '/item3',
      'desc': 'item description'
   },
   {
      'id': 88,
      'title': 'Item Title 4',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Micro Bags',
      'linkcategory': 'micro-bags',
      'src': '',
      'path': '/item4',
      'desc': 'item description'
   },
   {
      'id': 89,
      'title': 'Item Title 5',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Micro Bags',
      'linkcategory': 'micro-bags',
      'src': '',
      'path': '/item5',
      'desc': 'item description'
   },
   {
      'id': 90,
      'title': 'Item Title 6',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'BAGS',
      'category': 'Micro Bags',
      'linkcategory': 'micro-bags',
      'src': '',
      'path': '/item6',
      'desc': 'item description'
   },
]

export const WomensSneakersData = [
   {
      'id': 91,
      'title': 'Lacoste Sneakers',
      'price': 160,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Sneakers',
      'linkcategory': 'sneakers',
      'src': '/img/WOMENS/SNEAKERS/Lacoste Sneakers.jpg',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/WOMENS/SNEAKERS/Lacoste Sneakers.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 92,
      'title': 'Givenchy Sneakers',
      'price': 950,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Sneakers',
      'linkcategory': 'sneakers',
      'src': '/img/WOMENS/SNEAKERS/Givenchy Sneakers.jpeg',
      'path': '/item2',
      'desc': 'item description',
      'arr': ['/img/WOMENS/SNEAKERS/Givenchy Sneakers.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 93,
      'title': 'Tommy Hilfiger Sneakers',
      'price': 190,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Sneakers',
      'linkcategory': 'sneakers',
      'src': '/img/WOMENS/SNEAKERS/Tommy Hilfiger Sneakers.png',
      'path': '/item3',
      'desc': 'item description',
      'arr': ['/img/WOMENS/SNEAKERS/Tommy Hilfiger Sneakers.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 94,
      'title': 'Adidas Originals Sneakers',
      'price': 120,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Sneakers',
      'linkcategory': 'sneakers',
      'src': '/img/WOMENS/SNEAKERS/adidas Originals Sneakers.png',
      'path': '/item4',
      'desc': 'item description',
      'arr': ['/img/WOMENS/SNEAKERS/adidas Originals Sneakers.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 95,
      'title': 'New Balance 608s',
      'price': 250,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Sneakers',
      'linkcategory': 'sneakers',
      'src': '/img/WOMENS/SNEAKERS/New Balance 608 Sneakers.png',
      'path': '/item5',
      'desc': 'item description',
      'arr': ['/img/WOMENS/SNEAKERS/New Balance 608 Sneakers.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 96,
      'title': 'Gucci Ace Sneakers',
      'price': 1050,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Sneakers',
      'linkcategory': 'sneakers',
      'src': '/img/WOMENS/SNEAKERS/Gucci Ace Sneakers.png',
      'path': '/item6',
      'desc': 'item description',
      'arr': ['/img/WOMENS/SNEAKERS/Gucci Ace Sneakers.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const WomensHeelsData = [
   {
      'id': 97,
      'title': 'Butterfly High Heels',
      'price': 80,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Heels',
      'linkcategory': 'heels',
      'src': '/img/WOMENS/HEELS/Butterfly High Heels.png',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/WOMENS/HEELS/Butterfly High Heels.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 98,
      'title': 'GUESS High Heels',
      'price': 170,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Heels',
      'linkcategory': 'heels',
      'src': '/img/WOMENS/HEELS/GUESS High Heels.png',
      'path': '/item2',
      'desc': 'item description',
      'arr': ['/img/WOMENS/HEELS/GUESS High Heels.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 99,
      'title': 'Summer Laceup High Heels',
      'price': 80,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Heels',
      'linkcategory': 'heels',
      'src': '/img/WOMENS/HEELS/Summer Laceup High Heels.jpg',
      'path': '/item3',
      'desc': 'item description',
      'arr': ['/img/WOMENS/HEELS/Summer Laceup High Heels.jpg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 100,
      'title': 'Jimmy Choo High Heels',
      'price': 800,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Heels',
      'linkcategory': 'heels',
      'src': '/img/WOMENS/HEELS/Jimmy Choo High Heels.png',
      'path': '/item4',
      'desc': 'item description',
      'arr': ['/img/WOMENS/HEELS/Jimmy Choo High Heels.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 101,
      'title': 'Stiletto High Heels',
      'price': 140,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Heels',
      'linkcategory': 'heels',
      'src': '/img/WOMENS/HEELS/Stiletto High Heels.png',
      'path': '/item5',
      'desc': 'item description',
      'arr': ['/img/WOMENS/HEELS/Stiletto High Heels.png', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 102,
      'title': 'Tony Bianco High Heels',
      'price': 950,
      'gender': 'womens',
      'categories': 'SHOES',
      'category': 'Heels',
      'linkcategory': 'heels',
      'src': '/img/WOMENS/HEELS/Tony Bianco High Heels.jpeg',
      'path': '/item6',
      'desc': 'item description',
      'arr': ['/img/WOMENS/HEELS/Tony Bianco High Heels.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
]

export const WomensJewelryData = [
   {
      'id': 103,
      'title': 'Item Title 1',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Jewelry',
      'linkcategory': 'jewelry',
      'src': '',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 104,
      'title': 'Item Title 2',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Jewelry',
      'linkcategory': 'jewelry',
      'src': '',
      'path': '/item2',
      'desc': 'item description'
   },
   {
      'id': 105,
      'title': 'Item Title 3',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Jewelry',
      'linkcategory': 'jewelry',
      'src': '',
      'path': '/item3',
      'desc': 'item description'
   },
   {
      'id': 106,
      'title': 'Item Title 4',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Jewelry',
      'linkcategory': 'jewelry',
      'src': '',
      'path': '/item4',
      'desc': 'item description'
   },
   {
      'id': 107,
      'title': 'Item Title 5',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Jewelry',
      'linkcategory': 'jewelry',
      'src': '',
      'path': '/item5',
      'desc': 'item description'
   },
   {
      'id': 108,
      'title': 'Item Title 6',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Jewelry',
      'linkcategory': 'jewelry',
      'src': '',
      'path': '/item6',
      'desc': 'item description'
   },
]

export const WomensBeltsData = [
   {
      'id': 109,
      'title': 'Item Title 1',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Belts',
      'linkcategory': 'belts',
      'src': '',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 110,
      'title': 'Item Title 2',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Belts',
      'linkcategory': 'belts',
      'src': '',
      'path': '/item2',
      'desc': 'item description'
   },
   {
      'id': 111,
      'title': 'Item Title 3',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Belts',
      'linkcategory': 'belts',
      'src': '',
      'path': '/item3',
      'desc': 'item description'
   },
   {
      'id': 112,
      'title': 'Item Title 4',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Belts',
      'linkcategory': 'belts',
      'src': '',
      'path': '/item4',
      'desc': 'item description'
   },
   {
      'id': 113,
      'title': 'Item Title 5',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Belts',
      'linkcategory': 'belts',
      'src': '',
      'path': '/item5',
      'desc': 'item description'
   },
   {
      'id': 114,
      'title': 'Item Title 6',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Belts',
      'linkcategory': 'belts',
      'src': '',
      'path': '/item6',
      'desc': 'item description'
   },
]

export const WomensSunglassesData = [
   {
      'id': 115,
      'title': 'Item Title 1',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Sunglasses',
      'linkcategory': 'sunglasses',
      'src': '',
      'path': '/item1',
      'desc': 'item description',
      'arr': ['/img/MENS/T-SHIRTS/Givenchy Tee.jpeg', '/img/mens.jpg', '/img/shoes.jpg', '/img/trash.jpg', '/img/bags.jpg']
   },
   {
      'id': 116,
      'title': 'Item Title 2',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Sunglasses',
      'linkcategory': 'sunglasses',
      'src': '',
      'path': '/item2',
      'desc': 'item description'
   },
   {
      'id': 117,
      'title': 'Item Title 3',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Sunglasses',
      'linkcategory': 'sunglasses',
      'src': '',
      'path': '/item3',
      'desc': 'item description'
   },
   {
      'id': 118,
      'title': 'Item Title 4',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Sunglasses',
      'linkcategory': 'sunglasses',
      'src': '',
      'path': '/item4',
      'desc': 'item description'
   },
   {
      'id': 119,
      'title': 'Item Title 5',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Sunglasses',
      'linkcategory': 'sunglasses',
      'src': '',
      'path': '/item5',
      'desc': 'item description'
   },
   {
      'id': 120,
      'title': 'Item Title 6',
      'price': 'Price',
      'gender': 'womens',
      'categories': 'ACCESSORIES',
      'category': 'Sunglasses',
      'linkcategory': 'sunglasses',
      'src': '',
      'path': '/item6',
      'desc': 'item description'
   },
]